version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/apps/api"
    schedule:
      interval: "weekly"
      timezone: "Asia/Bangkok"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps)"
    groups:
      api-npm-non-major:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/apps/web"
    schedule:
      interval: "weekly"
      timezone: "Asia/Bangkok"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps)"
    groups:
      web-npm-non-major:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/apps/mobile"
    schedule:
      interval: "weekly"
      timezone: "Asia/Bangkok"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps)"
    groups:
      mobile-npm-non-major:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "Asia/Bangkok"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps)"
    groups:
      github-actions-non-major:
        update-types:
          - "minor"
          - "patch"
